---
- name: Create directrory for node exporter
  become: true
  file:
    state: directory
    path: "/opt/node_exporter"
    owner: "{{ ansible_user_id }}"
- name: Extract node exporter in the installation directory
  unarchive:
    copy: false
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/opt/node_exporter/"
    extra_opts: [--strip-components=1]
    creates: "/opt/node_exporter/node_exporter"
- name: Create node exporter service
  become: true
  template:
    src: templates/node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
  notify: restart node_exporter